baseURL = "https://blog.rickchen.info/"
languageCode = "zh-CN"
defaultContentLanguage = "zh-cn"
title = "聪了个颖"                         # site title  # 网站标题
theme = "LoveIt"
hasCJKLanguage = true                  # has chinese/japanese/korean ?  # 自动检测是否包含 中文\日文\韩文
summaryLength = 100
paginate = 4                           # shows the number of articles  # 首页显示文章数量
enableEmoji = true
googleAnalytics = ""                   # your google analytics id
disqusShortname = ""                   # your discuss shortname
enableGitInfo = true

pygmentsUseClasses = true
pygmentCodeFences = true
pygmentscodefencesguesssyntax = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[author]                               # essential                     # 必需
  name = "Rick Chen"

[blackfriday]
  smartypants = false

[[menu.main]]                          # config your menu  # 配置菜单
  name = "主页"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "归档"
  weight = 20
  identifier = "archive"
  url = "/posts/"
[[menu.main]]
  name = "标签"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "关于"
  weight = 40
  identifier = "about"
  url = "/about/"


[params]
  version = "0.2.X"
  subTitle = "blog.rickchen.info"                                       # site's subTitle  # 网站二级标题
  footerSlogan = ""                                   # site's footer slogan  # 网站页脚标语
  keywords = ["聪了个颖","博客","技术"]                                  # site's keywords  # 网站关键字
  description = "聪了个颖的博客"                        # site's description  # 网站描述
  enableMathJax = true                                                 # enable mathjax  # 是否使用mathjax（数学公式）
  enableSummary = true                                                 # display the article summary  # 是否显示文章摘要
  mainSections = ["posts","post"]
  gitRepo = "https://github.com/chency147/blog"

[params.header]
  # 桌面端导航栏模式 ("fixed", "normal", "auto")
  desktopMode = "fixed"
  # 移动端导航栏模式 ("fixed", "normal", "auto")
  mobileMode = "auto"
  # LoveIt 新增 | 0.2.0 页面头部导航栏标题配置
  [params.header.title]
    # LOGO 的 URL
    logo = ""
    # 标题名称
    name = "聪了个颖"
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    pre = '<i class="far fa-kiss-wink-heart fa-fw"></i>'
    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
    post = ""
    # LoveIt 新增 | 0.2.5 是否为标题显示打字机动画
    typeit = true
[params.home]
  # LoveIt 新增 | 0.2.0 RSS 文章数目
  rss = 10
  # 主页个人信息
  [params.home.profile]
    enable = true
    # Gravatar 邮箱，用于优先在主页显示的头像
    gravatarEmail = ""
    # 主页显示头像的 URL
    avatarURL = "https://cdn.jsdelivr.net/gh/chency147/image-bed@main/img/20201122213325.png"
    # LoveIt 更改 | 0.2.7 主页显示的网站标题 (支持 HTML 格式)
    title = ""
    # 主页显示的网站副标题
    subtitle = "勤能补拙"
    # 是否为副标题显示打字机动画
    typeit = true
    # 是否显示社交账号
    social = true
    # LoveIt 新增 | 0.2.0 免责声明 (支持 HTML 格式)
    disclaimer = ""
  # 主页文章列表
  [params.home.posts]
    enable = true
    # 主页每页显示文章数量
    paginate = 6
    # LoveIt 删除 | 0.2.0 被 params.page 中的 hiddenFromHomePage 替代
    # 当你没有在文章前置参数中设置 "hiddenFromHomePage" 时的默认行为
    defaultHiddenFromHomePage = false
  
# Your socail's url
[social]

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
[markup.highlight]
  noClasses = false
[markup.tableOfContents]
  startLevel = 2
  endLevel = 6

[params.page]
  twemoji = true
  lightgallery = true
  linkToMarkdown = true
  fontawesome = true
  fraction = true

[params.page.share]
  enable = true
  Twitter = true
  Facebook = true
  Linkedin = false
  Whatsapp = false
  Pinterest = false
  Tumblr = false
  HackerNews = false
  Reddit = false
  VK = false
  Buffer = false
  Xing = false
  Line = true
  Instapaper = false
  Pocket = false
  Digg = false
  Stumbleupon = false
  Flipboard = false
  Weibo = true
  Renren = false
  Myspace = false
  Blogger = false
  Baidu = true
  Odnoklassniki = false
  Evernote = false
  Skype = false
  Trello = false
  Mix = false

[languages.zh-cn]
  weight = 2
  # 网站语言, 仅在这里 CN 大写
  languageCode = "zh-CN"
  # 语言名称
  languageName = "简体中文"
  # 是否包括中日韩文字
  hasCJKLanguage = true
  # 默认每页列表显示的文章数目
  paginate = 12
  # [UA-XXXXXXXX-X] 谷歌分析代号
  googleAnalytics = ""
  # 版权描述，仅仅用于 SEO
  copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
  [languages.zh-cn.params.social]
    GitHub = "chency147"
    Weibo = "chency147"
    Zhihu = "chen-cong-ying-92"
    Douban = "152377415"
    Bilibili = "1622087"
    Steam = "chency147"
    RSS = true
[params.search]
  enable = true
  # 搜索引擎的类型 ("lunr", "algolia")
  type = "lunr"
  # 文章内容最长索引长度
  contentLength = 4000
  # 搜索框的占位提示语
  placeholder = ""
  # LoveIt 新增 | 0.2.1 最大结果数目
  maxResultLength = 10
  # LoveIt 新增 | 0.2.3 结果内容片段长度
  snippetLength = 50
  # LoveIt 新增 | 0.2.1 搜索结果中高亮部分的 HTML 标签
  highlightTag = "em"
  # LoveIt 新增 | 0.2.4 是否在搜索索引中使用基于 baseURL 的绝对路径
  absoluteURL = false

# 评论系统设置
  [params.page.comment]
    enable = true
    # Gitalk comment config (https://github.com/gitalk/gitalk)
    # Gitalk 评论系统设置 (https://github.com/gitalk/gitalk)
    [params.page.comment.gitalk]
      enable = true
      owner = "chency147"
      repo = "blog"
      clientId = "#GITALK_CLIENT_ID#"
      clientSecret = "#GITALK_CLIENT_SECRET#"
  # LoveIt 新增 | 0.2.10 网站 SEO 配置
  [params.seo]
    # 图片 URL
    image = "https://cdn.jsdelivr.net/gh/chency147/image-bed@main/img/20201122213325.png"
    # 缩略图 URL
    thumbnailUrl = "https://cdn.jsdelivr.net/gh/chency147/image-bed@main/img/20201122213325.png"

  # LoveIt 新增 | 0.2.0 网站分析配置
  [params.analytics]
    enable = true
    # Google Analytics
    [params.analytics.google]
      id = "G-T8PLEDPWE5"
      # 是否匿名化用户 IP
      anonymizeIP = true

  # 网站验证代码，用于 Google/Bing/Yandex/Pinterest/Baidu
  [params.verification]
    google = "8PxTMCz1toArryLo82wxbuenoAZGQS0g-VhbYo4Mx-8"
    bing = "5C16B907CBB005533DCEBE5C88A6D311"
    yandex = ""
    pinterest = ""
    baidu = "code-5uvntKqMCO"
